apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tinyforge

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - dashboard-api.yaml
  - training-worker.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app: tinyforge
  version: "0.2.0"

commonAnnotations:
  app.kubernetes.io/name: tinyforge
  app.kubernetes.io/version: "0.2.0"
  app.kubernetes.io/part-of: tinyforge-platform
